name: Master

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Running
        run: |
          echo "Running!"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2003661@ds.study.iitm.ac.in
        run: echo "Hello, world!"
